<script>
  import { Link, navigate } from "svelte-routing";
</script>

<footer class="footer">
  <div class="footer-1 container">
    <ul>
      <li><a href="#">Inicio</a></li>
      <li><a href="#">Ecosistema Marino</a></li>
      <li><a href="#">Equipo</a></li>
      <li><a href="#">Testimonios</a></li>
      <li><a href="#">Contactos</a></li>
    </ul>
  </div>
  <div class="footer-content footer-2">
    <div class="footer-logo pulsate-bck">Ocean Fighters</div>
    <div class="footer-links" />
    <div class="footer-social" />
    <div class="footer-credit">© 2023 Todos los derechos reservados</div>
  </div>
</footer>

<style>
  footer {
    width: 100%;
  }
  .footer {
    padding: 20px;
    text-align: center;
    bottom: 0;
  }

  .footer-content {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
  }

  .footer-logo {
    font-size: 24px;
    font-weight: bold;
    margin-bottom: 10px;
  }

  .footer-links {
    display: flex;
    justify-content: center;
    margin-bottom: 10px;
  }

  .footer-social {
    margin-bottom: 10px;
  }

  .footer-credit {
    color: #666;
    font-size: 14px;
  }

  .container {
    max-width: 1200px;
    margin: 0 auto;
  }

  .footer {
    padding-top: 40px;
    background-color: #082543;
  }

  .footer-1 {
    padding-bottom: 40px;
  }

  .footer-1 ul {
    display: flex;
    justify-content: space-between;
  }

  .footer-1 ul li a {
    color: #fefffb;
    text-decoration: none;
  }

  .footer-1 ul li a:hover {
    color: #efbc70;
  }

  .footer-2 {
    padding: 15px;
    text-align: center;
    color: #fefffb;
    background-color: #082543;
  }

  .pulsate-bck {
    -webkit-animation: pulsate-bck 2s ease-in-out infinite both;
    animation: pulsate-bck 2s ease-in-out infinite both;
  }

  /* ----------------------------------------------
 * Generated by Animista on 2023-8-14 20:56:6
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

  /**
 * ----------------------------------------
 * animation pulsate-bck
 * ----------------------------------------
 */
  @-webkit-keyframes pulsate-bck {
    0% {
      -webkit-transform: scale(1);
      transform: scale(1);
    }
    50% {
      -webkit-transform: scale(0.9);
      transform: scale(0.9);
    }
    100% {
      -webkit-transform: scale(1);
      transform: scale(1);
    }
  }
  @keyframes pulsate-bck {
    0% {
      -webkit-transform: scale(1);
      transform: scale(1);
    }
    50% {
      -webkit-transform: scale(0.9);
      transform: scale(0.9);
    }
    100% {
      -webkit-transform: scale(1);
      transform: scale(1);
    }
  }
</style>
